### ISSUE TITLE
Cache all topic tags

### ISSUE THREAD

**Issue by dragfire** [dragfire/leetup#18]
Have all topic-tags cached.
Topics: `[array, dynamic-programming, string, math, tree, depth-first-search, hash-table, greedy, binary-search, breadth-first-search, sort, two-pointers, stack, backtracking, design, bit-manipulation, graph, linked-list, heap, union-find, sliding-window, divide-and-conquer, trie, recursion, segment-tree, ordered-map, geometry, queue, minimax, brainteaser, binary-indexed-tree, line-sweep, random, topological-sort, binary-search-tree, rolling-hash, rejection-sampling, reservoir-sampling, memoization, suffix-array]`

Sample GraphQL request: 
```json
{
  "operationName": "getTopicTag",
  "variables": {
    "slug": "array"
  },
  "query": "query getTopicTag($slug: String!) {\n  topicTag(slug: $slug) {\n    name\n    translatedName\n    slug\n    questions {\n      status\n      questionId\n      questionFrontendId\n      title\n      titleSlug\n      translatedTitle\n      stats\n      difficulty\n      isPaidOnly\n      topicTags {\n        name\n        translatedName\n        slug\n        __typename\n      }\n      companyTags {\n        name\n        translatedName\n        slug\n        __typename\n      }\n      __typename\n    }\n    frequencies\n    __typename\n  }\n  favoritesLists {\n    publicFavorites {\n      ...favoriteFields\n      __typename\n    }\n    privateFavorites {\n      ...favoriteFields\n      __typename\n    }\n    __typename\n  }\n}\n\nfragment favoriteFields on FavoriteNode {\n  idHash\n  id\n  name\n  isPublicFavorite\n  viewCount\n  creator\n  isWatched\n  questions {\n    questionId\n    title\n    titleSlug\n    __typename\n  }\n  __typename\n}\n"
}
```

Relevant code: https://github.com/dragfire/leetup/blob/master/src/service/leetcode.rs#L414-L437

**Comment by jkurian** [comment]
Hi, I will try to complete this issue. Just so my understanding is correct, do you want to update the `getQuestionDetail` query or make another GQL request for the tags? 

After the tags are retrieved they will be cached in the `Leetcode` KVStore cache? Where would these tags be used?

**Comment by dragfire** [comment]
We want this: `leetup list -t <tag>` to work: https://github.com/dragfire/leetup/blob/master/src/cmd.rs#L15  So, will need to make a GQL request for each tag and cache it, might wanna do this in the background once. May wanna use this: https://github.com/dragfire/leetup/blob/master/src/service/pool.rs but I am fine with just spawning a thread.
Later we will just query the cache for tags.

I am fine with making a network request for tag queries and make the query work, we can cache it later also in a separate PR.

**Comment by jkurian** [comment]
Ah ok that makes a lot more sense. I'll give it a go. Thanks!

**Comment by jkurian** [comment]
So I have `leetup list -t <tag>` working but I don't think its the way you had in mind. I run the GQL query to get the list of question_ids for that tag, and then filter the questions based on the returned ids within the `list_problems` function. This basically makes it easy to have the query work because we are reusing the `list_problems` but of course we are making 2 network requests now (one for the question_ids under the tag, and one for all the questions). I can also cache the questions after filtering, so any other requests for the same tag will be cached and not have to go through any network requests.

I am wondering if you would be ok with this approach? If so I can open a PR for you to take a look. Otherwise I can figure out what fields of the GQL query are required for the query to work so we only do 1 network request.

**Comment by dragfire** [comment]
I think I am okay with that. Shoot a PR, we will discuss it there!
